name: Build and Deploy Dev Environment

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the dev repository
      - name: Checkout Dev Repository
        uses: actions/checkout@v3

      # Pull the latest changes from the production repository
      - name: Pull Production Repository
        run: |
          git submodule add https://github.com/msarson/discourse-highlightjs-clarion.git common
          git submodule update --remote --merge

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install Sass globally
      - name: Install Sass globally
        run: npm install -g sass

      # Install dependencies in the dev folder
      - name: Install dependencies in dev folder
        working-directory: dev
        run: npm install

      # Generate Color Variables
      - name: Generate Color Variables
        run: |
          node dev/generate-colors.js

      # Check if generated-colors.scss exists
      - name: Verify generated colors file
        run: ls -la dev/common/generated-colors.scss

      # Add import to common.scss
      - name: Modify SCSS files
        run: |
          echo '@import "./generated-colors.scss";' | cat - dev/common/common.scss > temp && mv temp dev/common/common.scss

      # Compile SCSS
      - name: Compile SCSS
        working-directory: dev
        run: npm run build-scss

      # Clean up SCSS files
      - name: Clean up SCSS files
        run: |
          rm dev/common/common.scss
          rm dev/common/color_definitions.scss
          rm dev/common/generated-colors.scss

      # Commit and push changes back to the dev repository
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add -A  # Stages all new, modified, and deleted files
          git commit -m "Automated extraction and SCSS compilation"
          git push origin HEAD:main
        continue-on-error: true  # Prevent immediate failure, see what happens
