name: Build and Deploy Dev Environment

on:
  push:
      branches:
        - master  # You can change this to the target branch where the PRs are opened

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.repository == 'msarson/discourse-dev-highlight-clarion'  # Only run this workflow for this repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest production subtree
        run: |
          git submodule update --init --recursive
          git submodule update --remote --merge

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Sass globally
        run: npm install -g sass

      - name: Install dependencies in dev folder
        working-directory: dev
        run: npm install

      # Create dev/common folder to ensure it exists
      - name: Create dev/common folder
        run: mkdir -p dev/common

      # Copy SCSS files to dev/common
      - name: Copy SCSS files to dev
        run: |
          cp production/common/common.scss dev/common/common.scss
          cp production/common/color_definitions.scss dev/common/color_definitions.scss
          cp production/common/clarion-language.js dev/common/clarion-language.js

      # Generate light and dark mode colors
      - name: Generate Color Variables
        run: |
          node dev/generate-colors.js

      # Add import to common.scss
      - name: Modify SCSS files
        run: |
          echo '@import "./generated-colors.scss";' | cat - dev/common/common.scss > temp && mv temp dev/common/common.scss

      # Compile SCSS
      - name: Compile SCSS
        working-directory: dev
        run: npm run build-scss  

      # Clean up SCSS files that were generated above - testing pat
      - name: Clean up generated-colors.scss
        run: |
          rm dev/common/generated-colors.scss

      # Commit and push changes only if PAT_TOKEN is available
      - name: Commit and push changes
        if: ${{ secrets.PAT_TOKEN != '' }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add -A  # Stages all new, modified, and deleted files
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Automated extraction and SCSS compilation"
            git push "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/msarson/discourse-dev-highlight-clarion.git" HEAD:master
          fi
        
        
