name: Build and Deploy Dev Environment

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest production subtree
        run: |
          git submodule update --init --recursive
          git submodule update --remote --merge

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Sass globally
        run: npm install -g sass

      - name: Install dependencies in dev folder
        working-directory: dev
        run: npm install

      # List source files before copying
      - name: List common directory contents before copying
        run: ls -la production/common

      # Create dev/common folder to ensure it exists
      - name: Create dev/common folder
        run: mkdir -p dev/common

      # Copy SCSS files to dev/common
      - name: Copy SCSS files to dev
        run: |
          cp production/common/common.scss dev/common/common.scss
          cp production/common/color_definitions.scss dev/common/color_definitions.scss
          cp production/common/clarion-language.js dev/common/clarion-language.js

      # # List dev/common directory contents after copying
      # - name: List dev/common directory contents after copying
      #   run: ls -la dev/common

      # - name: Verify contents of common.scss
      #   run: cat dev/common/common.scss

      # # List dev/common to verify the files were copied
      # - name: List dev/common folder contents
      #   run: ls -la dev/common

      # Generate light and dark mode colors
      - name: Generate Color Variables
        run: |
          node dev/generate-colors.js

      # # Check if generated-colors.scss exists
      # - name: Verify generated colors file
      #   run: ls -la dev/common/generated-colors.scss

      # # Show contents of generated-colors.scss
      # - name: Show contents of generated-colors.scss
      #   run: cat dev/common/generated-colors.scss

      # Add import to common.scss
      - name: Modify SCSS files
        run: |
          echo '@import "./generated-colors.scss";' | cat - dev/common/common.scss > temp && mv temp dev/common/common.scss

      # - name: Verify contents of common.scss after modification
      #   run: cat dev/common/common.scss 

      # Compile SCSS
      - name: Compile SCSS
        working-directory: dev
        run: npm run build-scss  

      # Clean up SCSS files that were generated above.
      - name: Clean up SCSS file leaving only production files
        run: |
          rm dev/common/generated-colors.scss

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add -A  # Stages all new, modified, and deleted files
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Automated extraction and SCSS compilation"
            git push "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/msarson/discourse-highlightjs-clarion.git" HEAD:master
          fi
        
        
